-- MySQL Script generated by MySQL Workbench
-- Sun Sep 17 11:08:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`subscription_plans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subscription_plans` (
  `plan_id` INT NOT NULL,
  `plan_type` VARCHAR(45) NOT NULL,
  `payment_id` TEXT NOT NULL,
  `payment_method` VARCHAR(45) NOT NULL,
  `sub_date` DATETIME NOT NULL,
  PRIMARY KEY (`plan_id`),
  UNIQUE INDEX `payment_id_UNIQUE` (`payment_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`landlords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`landlords` (
  `landlord_id` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` MEDIUMTEXT NOT NULL,
  `profile_image` TINYTEXT NULL,
  `plan_id` INT NOT NULL,
  `address` MEDIUMTEXT NOT NULL,
  `verification_status` INT NOT NULL,
  PRIMARY KEY (`landlord_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) VISIBLE,
  UNIQUE INDEX `profile_image_UNIQUE` (`profile_image` ASC) VISIBLE,
  UNIQUE INDEX `plan_id_UNIQUE` (`plan_id` ASC) VISIBLE,
  CONSTRAINT `fk_landlords_subscription_plan1`
    FOREIGN KEY (`plan_id`)
    REFERENCES `mydb`.`subscription_plans` (`plan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tenants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tenants` (
  `tenant_id` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` MEDIUMTEXT NOT NULL,
  `profile_image` TINYTEXT NULL,
  `document_id` INT NOT NULL,
  `plan_id` INT NOT NULL,
  `address` MEDIUMTEXT NOT NULL,
  `verification_status` INT NULL,
  PRIMARY KEY (`tenant_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) VISIBLE,
  UNIQUE INDEX `profile_image_UNIQUE` (`profile_image` ASC) VISIBLE,
  UNIQUE INDEX `plan_id_UNIQUE` (`plan_id` ASC) VISIBLE,
  UNIQUE INDEX `document_id_UNIQUE` (`document_id` ASC) VISIBLE,
  CONSTRAINT `fk_tenants_subscription_plan1`
    FOREIGN KEY (`plan_id`)
    REFERENCES `mydb`.`subscription_plans` (`plan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admins` (
  `admin_id` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` MEDIUMTEXT NOT NULL,
  `profile_image` TINYTEXT NOT NULL,
  PRIMARY KEY (`admin_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`properties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`properties` (
  `property_id` INT NOT NULL,
  `landlord_id` INT NOT NULL,
  PRIMARY KEY (`property_id`),
  UNIQUE INDEX `landlord_id_UNIQUE` (`landlord_id` ASC) VISIBLE,
  CONSTRAINT `landlord_to_properties`
    FOREIGN KEY (`landlord_id`)
    REFERENCES `mydb`.`landlords` (`landlord_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rooms` (
  `room_id` INT NOT NULL,
  `property_id` INT NOT NULL,
  `room_name` VARCHAR(100) NOT NULL,
  `verification_status` INT NOT NULL,
  `state` VARCHAR(100) NOT NULL,
  `district` VARCHAR(100) NOT NULL,
  `zipcode` INT NOT NULL,
  `remark` LONGTEXT NULL,
  `no_of_rooms` INT NOT NULL,
  `attached_kitchen` INT NOT NULL,
  `attached_bathroom` INT NOT NULL,
  `include_water_price` INT NOT NULL,
  `include_electricity_price` INT NOT NULL,
  `rating` INT NULL,
  PRIMARY KEY (`room_id`),
  INDEX `property_to_rooms_idx` (`property_id` ASC) VISIBLE,
  CONSTRAINT `property_to_rooms`
    FOREIGN KEY (`property_id`)
    REFERENCES `mydb`.`properties` (`property_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`images` (
  `image_id` INT NOT NULL,
  `room_id` INT NOT NULL,
  PRIMARY KEY (`image_id`),
  INDEX `room_to_images_idx` (`room_id` ASC) VISIBLE,
  CONSTRAINT `room_to_images`
    FOREIGN KEY (`room_id`)
    REFERENCES `mydb`.`rooms` (`room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`documents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`documents` (
  `document_id` INT NOT NULL,
  `object_id` INT NOT NULL,
  PRIMARY KEY (`document_id`),
  UNIQUE INDEX `object_id_UNIQUE` (`object_id` ASC) VISIBLE,
  CONSTRAINT `landord_to_documents`
    FOREIGN KEY (`object_id`)
    REFERENCES `mydb`.`landlords` (`landlord_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tenant_to_documents`
    FOREIGN KEY (`object_id`)
    REFERENCES `mydb`.`tenants` (`tenant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
